---
title: Ik heb een boek voor je gemaakt
hero_image: images/banner.png
description: Maak een boek met meerdere pagina's om een verhaal te vertellen of feiten te delen
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - title: Inleiding
  - title: Jouw idee
  - title: Bouwen en testen
    completion: engaged
  - title: Deel
  - title: Reflectie
    completion: internal
  - title: Verbeter je project
    completion: external
  - title: Wat kun je verder nog doen?
