---
title: Ik heb een boek voor je gemaakt
hero_image: images/banner.png
description: Maak een boek met meerdere pagina's om een verhaal te vertellen of feiten te delen
meta_title: Scratch-programmeerprojecten voor kinderen en tieners | Ik heb een boek voor je gemaakt
meta_description: Leer coderen in Scratch met de programmeerprojecten voor kinderen en tieners van de Raspberry Pi Foundation. Maak een digitaal Scratch-boek voor iemand om wie je geeft.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Je gaat maken
  - 
    title: Jouw idee
  - 
    title: Plan je boek
  - 
    title: Bouwen en testen
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Deel en speel
