---
title: Ik heb een boek voor je gemaakt
hero_image: images/banner.png
description: Maak een boek met meerdere pagina's om een verhaal te vertellen of feiten te delen
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - title: Je gaat maken
  - title: Jouw idee
  - title: Plan je boek
  - title: Bouwen en testen
    completion:
      - engaged
      - internal
  - title: Checklist
    completion:
      - external
  - title: Deel en speel