---
title: I made you a book
hero_image: images/banner.png
description: Create a book with multiple pages to tell a story or share facts
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
- title: You will make
- title: Your idea
- title: Plan your book 
- title: Build and test
  completion:
  - engaged
  - internal
- title: Checklist
  completion:
  - external
- title: Share
- title: What next?