---
title: मैंने आपको एक किताब बनाई
hero_image: images/banner.png
description: एक कहानी कहने या तथ्य साझा करने के लिए कई पृष्ठों के साथ एक पुस्तक बनाएं
meta_title: बच्चों और टीनएजर्स के लिए स्क्रैच कोडिंग प्रोजेक्ट | मैंने तुम्हारे लिए एक किताब बनाई
meta_description: बच्चों और टीनएजर्स के लिए रास्पबेरी पाई फाउंडेशन की कोडिंग प्रोजेक्ट से शुरुआत से कोड करना सीखें। किसी ऐसे व्यक्ति के लिए स्क्रैच डिजिटल बुक बनाएं जिसकी आप परवाह करते हैं
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: आप बनाएंगे
  - 
    title: आपका विचार
  - 
    title: अपनी पुस्तक की योजना बनाएं
  - 
    title: निर्माण और परीक्षण
    completion:
      - engaged
      - internal
  - 
    title: जांच सूची
    completion:
      - external
  - 
    title: साझा करें और खेलें
