---
title: 私はあなたに本を作りました
hero_image: images/banner.png
description: 物語を伝えたり事実を共有したりするために、複数ページの本を作成します
meta_title: 子供と十代の若者向けのScratch コーディングプロジェクト | 私はあなたに本を作りました
meta_description: Raspberry Pi Foundationの子供と十代の若者向けのコーディングプロジェクトで、Scratchによるコーディングを学びましょう。大切な人のためにデジタルブックを作成します。
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: はじめに
  - 
    title: あなたのアイデア
  - 
    title: 本を考える
  - 
    title: 作って試す
    completion:
      - external
      - internal
  - 
    title: チェックリスト
    completion:
      - external
  - 
    title: 共有して遊ぶ
