---
title: Napravio sam ti knjigu
hero_image: images/banner.png
description: Napravite knjigu s više stranica da ispričate priču ili podijelite činjenice
meta_title: Scratch coding projects for kids and teens | I made you a book
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch digital book for someone you care about.
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Vi ćete napraviti
  - 
    title: Vaša ideja
  - 
    title: Planirajte svoju knjigu
  - 
    title: Napravite i testirajte
    completion:
      - engaged
      - internal
  - 
    title: Spisak
    completion:
      - external
  - 
    title: Podijelite i igrajte se
