---
title: Dw i wedi creu llyfr i ti
hero_image: images/banner.png
description: Creu llyfr gyda sawl tudalen i adrodd stori neu rannu ffeithiau
meta_title: Scratch coding projects for kids and teens | I made you a book
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch digital book for someone you care about.
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: You will make
  - 
    title: Dy syniad
  - 
    title: Plan your book
  - 
    title: Build and test
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Share and play
