---
title: Eu fiz um livro para você
hero_image: images/banner.png
description: Crie um livro com várias páginas para contar uma história ou compartilhar fatos
meta_title: Scratch coding projects for kids and teens | I made you a book
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch digital book for someone you care about.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: You will make
  - 
    title: A sua idéia
  - 
    title: Plan your book
  - 
    title: Build and test
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Share and play
  - 
    title: E agora?
