---
title: Eu fiz um livro para você
hero_image: images/banner.png
description: Crie um livro com várias páginas para contar uma história ou compartilhar fatos
meta_title: Projetos de programação Scratch para crianças e adolescentes | Eu fiz um livro para você
meta_description: Aprenda a programar no Scratch com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça um livro digital do Scratch para alguém de quem você gosta.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - title: Você vai fazer
  - title: Sua ideia
  - title: Planeje seu livro
  - title: Construir e testar
    completion:
      - engaged
      - internal
  - title: Lista de tarefas
    completion:
      - external
  - title: Compartilhar e jogar