---
title: ನಾನು ನಿಮಗೆ ಪುಸ್ತಕವನ್ನು ತಯಾರಿಸಿದ್ದೇನೆ
hero_image: images/banner.png
description: ಕಥೆಯನ್ನು ಹೇಳುವುದಕ್ಕೆ ಅಥವಾ ವಾಸ್ತವನ್ನು ಹಂಚಿಕೊಳ್ಳುವುದಕ್ಕೆ ಬಹು ಪುಟಗಳ ಪುಸ್ತಕವನ್ನು ತಯಾರಿಸಿ
meta_title: Scratch coding projects for kids and teens | I made you a book
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch digital book for someone you care about.
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: You will make
  - 
    title: ನಿಮ್ಮ ಕಲ್ಪನೆ
  - 
    title: Plan your book
  - 
    title: Build and test
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Share and play
