---
title: Te hice un libro
hero_image: images/banner.png
description: Crea un libro con varias páginas para contar una historia o compartir hechos
meta_title: Proyectos de codificación de Scratch para niños y adolescentes | Te hice un libro
meta_description: Aprende a codificar en Scratch con los proyectos de codificación de la Fundación Raspberry Pi para niños y adolescentes. Crea un libro digital para alguien en particular.
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Lo que harás
  - 
    title: Tu idea
  - 
    title: Planifica tu libro
  - 
    title: Construye y prueba
    completion:
      - engaged
      - internal
  - 
    title: Lista de control
    completion:
      - external
  - 
    title: Comparte y juega
