---
title: Te hice un libro
hero_image: images/banner.png
description: Crea un libro con varias páginas para contar una historia o compartir hechos
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Lo que harás
  - 
    title: Tu idea
  - 
    title: Plan your book
  - 
    title: Construye y prueba
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Comparte y juega
  - 
    title: '¿Qué sigue?'
