---
title: لقد صنعت لك كتابا
hero_image: images/banner.png
description: أنشئ كتابًا من عدة صفحات لسرد قصة أو مشاركة الحقائق
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - 
    title: المقدمة
  - 
    title: فكرتك
  - 
    title: بناء واختبار
    completion: internal
  - 
    title: Reflection
    completion: external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: ما هي الخطوة التالية؟
