---
title: لقد صنعت لك كتابا
hero_image: images/banner.png
description: أنشئ كتابًا من عدة صفحات لسرد قصة أو مشاركة الحقائق
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: You will make
  - 
    title: فكرتك
  - 
    title: Plan your book
  - 
    title: Build and test
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Share and play
  - 
    title: ما هي الخطوة التالية؟
