---
title: Zrobiłem Tobie książkę
hero_image: images/banner.png
description: Zrób książkę z wieloma stronami, aby opowiedzieć historię lub podzielić się faktami
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - 
    title: Wprowadzenie
  - 
    title: Twój pomysł
  - 
    title: Buduj i testuj
    completion: engaged
  - 
    title: Udostępnij
    completion: internal
  - 
    title: Reflection
    completion: external
  - 
    title: Upgrade your project
  - 
    title: Co dalej?
