---
title: Zrobiłem Tobie książkę
hero_image: images/banner.png
description: Zrób książkę z wieloma stronami, aby opowiedzieć historię lub podzielić się faktami
meta_title: Projekty kodowania scratch dla dzieci i młodzieży | Zrobiłem ci książkę
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch digital book for someone you care about.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: You will make
  - 
    title: Twój pomysł
  - 
    title: Plan your book
  - 
    title: Build and test
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: Share and play
  - 
    title: Co dalej?
