---
title: Jag har gjort en bok till dig
hero_image: images/banner.png
description: Skapa en bok med flera sidor för att berätta en historia eller dela fakta
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - title: Du kommer skapa
  - title: Din idé
  - title: Planera din bok
  - title: Bygg och testa
    completion:
      - engaged
      - internal
  - title: Checklista
    completion:
      - external
  - title: Dela och spela