---
title: Σου έφτιαξα ένα βιβλίο
hero_image: images/banner.png
description: Δημιούργησε ένα βιβλίο με πολλές σελίδες για να πεις μια ιστορία ή να μοιραστείς γεγονότα
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - title: Εισαγωγή
  - title: Η ιδέα σου
  - title: Δημιουργία κι έλεγχος
    completion: engaged
    completion: internal
  - title: Αναστοχασμός
    completion: external
  - title: Αναβάθμιση του έργου σου
  - title: Κοινοποίηση
  - title: Πού θα βρεις βοήθεια
