---
title: Σου έφτιαξα ένα βιβλίο
hero_image: images/banner.png
description: Δημιούργησε ένα βιβλίο με πολλές σελίδες για να πεις μια ιστορία ή να μοιραστείς γεγονότα
meta_title: Έργα κώδικα σε Scratch για παιδιά και εφήβους | Σου έφτιαξα ένα βιβλίο
meta_description: Μάθε να προγραμματίζεις με Scratch με τα έργα κώδικα του Ιδρύματος Raspberry Pi για παιδιά και εφήβους. Δημιούργησε ένα ψηφικό βιβλίο στη Scratch για κάποιον ή κάποια που νοιάζεσαι.
pdf: resources/i-made-you-a-book.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Θα φτιάξεις
  - 
    title: Η ιδέα σου
  - 
    title: Σχεδίασε το βιβλίο σου
  - 
    title: Κατασκεύασε και δοκίμασε
    completion:
      - engaged
      - internal
  - 
    title: Λίστα ελέγχου
    completion:
      - external
  - 
    title: Μοίρασε και παίξε
