---
title: Je t'ai fait un livre
hero_image: images/banner.png
description: Crée un livre avec plusieurs pages pour raconter une histoire ou partager des informations
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - 
    title: Introduction
  - 
    title: Ton idée
  - 
    title: Construire et tester
  - 
    title: Partager
  - 
    title: Améliorer ton projet
  - 
    title: Réflexion
  - 
    title: Et ensuite ?
